# Site
name: "Diego E Nicole"
title: "DiegoENicole"
description: "Diego and Nicole's blog from Australia."
logo: 'assets/images/diego_e_nicole_crowned.png'
favicon: 'assets/images/diego_e_nicole_crowned.png'
baseurl: ''
google_analytics: 'UA-46278016-1'
disqus: 'demowebsite'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  diego:
    name: Diego
    display_name: Diego
    avatar: 'assets/images/diego_avatar.png'
    gravatar: e56154546cf4be74e393c62d1ae9f9d4
    email: 
    web: https://diegoenicole.github.ai
    # twitter: https://twitter.com/wowthemesnet
    description: "The Dude from Pin√©."
  
  nicole:
    name: Nicole
    display_name: Nicole
    avatar: 'assets/images/nicole_avatar.png'
    gravatar: b1cc14991db7a456fcd761680bbc8f81
    email: 
    web: https://diegoenicole.github.ai
    # twitter: https://twitter.com/wowthemesnet
    description: "The Dudess from Nave san Felice."
  
  diegoenicole:
    name: Diego E Nicole
    display_name: Diego E Nicole
    avatar: 'assets/images/diego_e_nicole_crowned.png'
    email: diegoenicole.australia@gmail.com
    web: https://diegoenicole.github.ai
    description: "These two guys are a single thing."

  hubi:
    name: Hubi
    display_name: Hubi
    avatar: 'assets/images/hubi_avatar.jpg'
    email: 
    web: 
    description: "The printer guy."
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
